In [21]:
# IMPORT LIBRARIES
import pandas as pd

In [22]:
# LOAD DATASET
df = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Raw_Data\Educational Attainment 2024(1 Year).csv")

In [23]:
# DATA OVERVIEW / INSPECTION
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Columns: 107 entries, Label (Grouping) to Puerto Rico!!Margin of Error
dtypes: object(107)
memory usage: 21.0+ KB

In [24]:
# REMOVE MARGIN OF ERROR COLUMNS
df = df.loc[:, ~ df.columns.str.contains("Margin of Error")]
df.head()

,Label (Grouping),United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"235,910,719","3,540,061","497,924","5,269,753","2,098,670","27,375,795","4,204,962","2,606,011","746,711",...,"4,996,558","20,576,959","2,153,204","474,347","6,112,828","5,631,460","1,268,689","4,172,638","409,344","2,428,065"
1,No schooling completed,"4,871,187","51,481","2,510","97,938","29,489","1,026,864","60,249","42,532","11,944",...,"69,836","564,138","32,110","4,759","104,600","95,801","13,595","44,139","4,603","45,010"
2,Nursery school,"78,695","1,045",403,"1,372",190,"11,186","1,685",969,499,...,"1,555","9,629",350,0,"2,598","1,353",730,816,0,499
3,Kindergarten,"63,452","1,126",114,866,120,"11,731","1,895",89,0,...,837,"7,214",170,0,"1,236","2,918",139,"1,024",81,829
4,1st grade,"109,962",966,15,"3,066",126,"30,289",613,"1,704","1,258",...,"1,589","14,059",78,0,"1,941","1,948",218,"1,295",0,"6,455"

In [25]:
# RENAME MAIN LABEL COLUMN
df.rename(columns={"Label (Grouping)": "Education_Level"}, inplace = True)
df.head()

,Education_Level,United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"235,910,719","3,540,061","497,924","5,269,753","2,098,670","27,375,795","4,204,962","2,606,011","746,711",...,"4,996,558","20,576,959","2,153,204","474,347","6,112,828","5,631,460","1,268,689","4,172,638","409,344","2,428,065"
1,No schooling completed,"4,871,187","51,481","2,510","97,938","29,489","1,026,864","60,249","42,532","11,944",...,"69,836","564,138","32,110","4,759","104,600","95,801","13,595","44,139","4,603","45,010"
2,Nursery school,"78,695","1,045",403,"1,372",190,"11,186","1,685",969,499,...,"1,555","9,629",350,0,"2,598","1,353",730,816,0,499
3,Kindergarten,"63,452","1,126",114,866,120,"11,731","1,895",89,0,...,837,"7,214",170,0,"1,236","2,918",139,"1,024",81,829
4,1st grade,"109,962",966,15,"3,066",126,"30,289",613,"1,704","1,258",...,"1,589","14,059",78,0,"1,941","1,948",218,"1,295",0,"6,455"

In [26]:
# RESHAPE/Transpose DATA (WIDE → LONG FORMAT)
education = df.melt( id_vars=["Education_Level"],
                  var_name="State",
                  value_name="Estimate")
education.head()

              Education_Level                    State     Estimate
0                      Total:  United States!!Estimate  235,910,719
1      No schooling completed  United States!!Estimate    4,871,187
2              Nursery school  United States!!Estimate       78,695
3                Kindergarten  United States!!Estimate       63,452
4                   1st grade  United States!!Estimate      109,962

In [27]:
#Check Unique Education Levels
education['Education_Level'].unique()

array(['Total:', '\xa0\xa0\xa0\xa0No schooling completed',
       '\xa0\xa0\xa0\xa0Nursery school', '\xa0\xa0\xa0\xa0Kindergarten',
       '\xa0\xa0\xa0\xa01st grade', '\xa0\xa0\xa0\xa02nd grade',
       '\xa0\xa0\xa0\xa03rd grade', '\xa0\xa0\xa0\xa04th grade',
       '\xa0\xa0\xa0\xa05th grade', '\xa0\xa0\xa0\xa06th grade',
       '\xa0\xa0\xa0\xa07th grade', '\xa0\xa0\xa0\xa08th grade',
       '\xa0\xa0\xa0\xa09th grade', '\xa0\xa0\xa0\xa010th grade',
       '\xa0\xa0\xa0\xa011th grade',
       '\xa0\xa0\xa0\xa012th grade, no diploma',
       '\xa0\xa0\xa0\xa0Regular high school diploma',
       '\xa0\xa0\xa0\xa0GED or alternative credential',
       '\xa0\xa0\xa0\xa0Some college, less than 1 year',
       '\xa0\xa0\xa0\xa0Some college, 1 or more years, no degree',
       "\xa0\xa0\xa0\xa0Associate's degree",
       "\xa0\xa0\xa0\xa0Bachelor's degree",
       "\xa0\xa0\xa0\xa0Master's degree",
       '\xa0\xa0\xa0\xa0Professional school degree',
       '\xa0\xa0\xa0\xa0Doctorate degree'], dtype=object)

In [28]:
#Remove Weird Characters
education['Education_Level'] = (education['Education_Level'].str.replace('재', '', regex=False).str.strip()
)
education.head()

          Education_Level                    State     Estimate
0                  Total:  United States!!Estimate  235,910,719
1  No schooling completed  United States!!Estimate    4,871,187
2          Nursery school  United States!!Estimate       78,695
3            Kindergarten  United States!!Estimate       63,452
4               1st grade  United States!!Estimate      109,962

In [29]:
#Remove United States Total
education = education[
    education['State'] != 'United States!!Estimate'
]
education.head()

           Education_Level              State   Estimate
25                  Total:  Alabama!!Estimate  3,540,061
26  No schooling completed  Alabama!!Estimate     51,481
27          Nursery school  Alabama!!Estimate      1,045
28            Kindergarten  Alabama!!Estimate      1,126
29               1st grade  Alabama!!Estimate        966

In [30]:
# CLEAN STATE NAMES
education["State"] = education["State"].str.replace("!!Estimate", "")
education.head()

           Education_Level    State   Estimate
25                  Total:  Alabama  3,540,061
26  No schooling completed  Alabama     51,481
27          Nursery school  Alabama      1,045
28            Kindergarten  Alabama      1,126
29               1st grade  Alabama        966

In [31]:
#Keep Only Important Degrees
important_levels = [
    'Regular high school diploma',
    "Bachelor's degree",
    "Master's degree",
    'Doctorate degree'
]

education = education[
    education['Education_Level'].isin(important_levels)
]
education.head()

                Education_Level    State Estimate
41  Regular high school diploma  Alabama  870,724
46            Bachelor's degree  Alabama  637,543
47              Master's degree  Alabama  304,002
49             Doctorate degree  Alabama   51,280
66  Regular high school diploma   Alaska  118,875

In [32]:
#Rename Education Categories
education['Education_Level'] = education[
    'Education_Level'
].replace({
    'Regular high school diploma': 'High_School',
    "Bachelor's degree": 'Bachelors',
    "Master's degree": 'Masters',
    'Doctorate degree': 'Doctorate'
})
education.head()

   Education_Level    State Estimate
41     High_School  Alabama  870,724
46       Bachelors  Alabama  637,543
47         Masters  Alabama  304,002
49       Doctorate  Alabama   51,280
66     High_School   Alaska  118,875

In [33]:
#Remove Commas From Numbers
education['Estimate']= (
    education['Estimate'].replace('[\$,]', '', regex=True)
)

In [34]:
#Convert Columns to Numeric
education['Estimate'] = pd.to_numeric(
    education['Estimate'],
    errors='coerce'
)

In [35]:
#Pivot Table
education_cleaned = education.pivot_table(
    index='State',
    columns='Education_Level',
    values='Estimate',
    aggfunc='sum'
).reset_index()
education_cleaned.head()

Education_Level       State  Bachelors  Doctorate  High_School  Masters
0                   Alabama     637543      51280       870724   304002
1                    Alaska      97736       7132       118875    44758
2                   Arizona    1101882      86023      1019002   522445
3                  Arkansas     359274      22866       575871   155632
4                California    6355683     554953      4924307  2806213

In [38]:
education.info()

<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 41 to 1324
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Education_Level  208 non-null    object
 1   State            208 non-null    object
 2   Estimate         208 non-null    int64
dtypes: int64(1), object(2)
memory usage: 6.5+ KB

In [37]:
#save the cleaned Data
education_cleaned.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Education_cleaned.csv", index=False)