In [69]:
# Import Liabraries
import pandas as pd

In [70]:
# Load Dataset
df = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Raw_Data\Employment Status 2024(1 Year).csv")

In [71]:
# Data Overview/ Inspection
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Columns: 107 entries, Label (Grouping) to Puerto Rico!!Margin of Error
dtypes: object(107)
memory usage: 6.0+ KB

In [72]:
# Remove Margin of error column
df = df.loc[: , ~df.columns.str.contains("Margin of Error")]
df.head()

,Label (Grouping),United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"276,249,478","4,160,138","586,083","6,193,806","2,477,205","32,089,744","4,901,957","3,042,260","863,403",...,"5,850,310","24,569,557","2,688,278","553,496","7,173,696","6,505,491","1,469,628","4,882,973","480,483","2,796,511"
1,In labor force:,"176,681,413","2,463,085","390,591","3,802,740","1,461,175","20,603,340","3,368,049","2,011,120","540,535",...,"3,700,754","16,153,610","1,875,908","358,864","4,679,200","4,229,462","806,719","3,191,606","311,849","1,328,934"
2,Civilian labor force:,"175,408,841","2,447,875","363,709","3,778,884","1,454,780","20,454,381","3,324,268","2,002,571","535,706",...,"3,680,703","16,034,699","1,868,725","358,176","4,546,485","4,167,685","804,058","3,187,642","307,647","1,325,458"
3,Employed,"167,292,666","2,344,294","342,028","3,606,425","1,399,240","19,240,700","3,182,088","1,903,478","508,349",...,"3,525,120","15,259,450","1,798,140","348,622","4,381,889","3,964,612","766,794","3,090,398","297,101","1,213,487"
4,Unemployed,"8,116,175","103,581","21,681","172,459","55,540","1,213,681","142,180","99,093","27,357",...,"155,583","775,249","70,585","9,554","164,596","203,073","37,264","97,244","10,546","111,971"

In [73]:
# Rename Label(Grouping) column
df.rename(columns={"Label (Grouping)": "Employment_Status"},inplace= True)
df.head()

,Employment_Status,United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"276,249,478","4,160,138","586,083","6,193,806","2,477,205","32,089,744","4,901,957","3,042,260","863,403",...,"5,850,310","24,569,557","2,688,278","553,496","7,173,696","6,505,491","1,469,628","4,882,973","480,483","2,796,511"
1,In labor force:,"176,681,413","2,463,085","390,591","3,802,740","1,461,175","20,603,340","3,368,049","2,011,120","540,535",...,"3,700,754","16,153,610","1,875,908","358,864","4,679,200","4,229,462","806,719","3,191,606","311,849","1,328,934"
2,Civilian labor force:,"175,408,841","2,447,875","363,709","3,778,884","1,454,780","20,454,381","3,324,268","2,002,571","535,706",...,"3,680,703","16,034,699","1,868,725","358,176","4,546,485","4,167,685","804,058","3,187,642","307,647","1,325,458"
3,Employed,"167,292,666","2,344,294","342,028","3,606,425","1,399,240","19,240,700","3,182,088","1,903,478","508,349",...,"3,525,120","15,259,450","1,798,140","348,622","4,381,889","3,964,612","766,794","3,090,398","297,101","1,213,487"
4,Unemployed,"8,116,175","103,581","21,681","172,459","55,540","1,213,681","142,180","99,093","27,357",...,"155,583","775,249","70,585","9,554","164,596","203,073","37,264","97,244","10,546","111,971"

In [74]:
# reshape/Transpose Data
employment = df.melt(
    id_vars="Employment_Status",
    var_name="State",
    value_name="Estimate")
employment.head()

               Employment_Status                    State     Estimate
0                         Total:  United States!!Estimate  276,249,478
1                In labor force:  United States!!Estimate  176,681,413
2          Civilian labor force:  United States!!Estimate  175,408,841
3                       Employed  United States!!Estimate  167,292,666
4                     Unemployed  United States!!Estimate    8,116,175

In [50]:
#Check Unique Education Levels
employment["Employment_Status"].unique()

array(['Total:', '\xa0\xa0\xa0\xa0In labor force:',
       '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Civilian labor force:',
       '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Employed',
       '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Unemployed',
       '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Armed Forces',
       '\xa0\xa0\xa0\xa0Not in labor force'], dtype=object)

In [75]:
#Remove Weird Characters
employment["Employment_Status"] = (employment["Employment_Status"].str.replace('재', '', regex=False).str.strip())
employment.head()

       Employment_Status                    State     Estimate
0                 Total:  United States!!Estimate  276,249,478
1        In labor force:  United States!!Estimate  176,681,413
2  Civilian labor force:  United States!!Estimate  175,408,841
3               Employed  United States!!Estimate  167,292,666
4             Unemployed  United States!!Estimate    8,116,175

In [76]:
# Clean State Name 
employment["State"]= employment["State"].str.replace("!!Estimate", "")
employment.head()

       Employment_Status          State     Estimate
0                 Total:  United States  276,249,478
1        In labor force:  United States  176,681,413
2  Civilian labor force:  United States  175,408,841
3               Employed  United States  167,292,666
4             Unemployed  United States    8,116,175

In [77]:
#Remove United States Total
employment = employment[
    (employment['State'] != 'United States') &
    (employment['Employment_Status'] != 'Total:')
]
employment.head()

        Employment_Status    State   Estimate
8         In labor force:  Alabama  2,463,085
9   Civilian labor force:  Alabama  2,447,875
10               Employed  Alabama  2,344,294
11             Unemployed  Alabama    103,581
12           Armed Forces  Alabama     15,210

In [79]:
#Pivot Table
employment = employment.pivot_table(
    index='State',
    columns='Employment_Status',
    values='Estimate',
    aggfunc='sum'
).reset_index()
employment.head()

Employment_Status,State,Armed Forces,Civilian labor force:,Employed,In labor force:,Not in labor force,Unemployed
0,Alabama,"15,210","2,447,875","2,344,294","2,463,085","1,697,053","103,581"
1,Alaska,"26,882","363,709","342,028","390,591","195,492","21,681"
2,Arizona,"23,856","3,778,884","3,606,425","3,802,740","2,391,066","172,459"
3,Arkansas,"6,395","1,454,780","1,399,240","1,461,175","1,016,030","55,540"
4,California,"148,959","20,454,381","19,240,700","20,603,340","11,486,404","1,213,681"

In [85]:
#Rename Columns
employment = employment.rename(columns={
    'Civilian labor force:': 'Labor_Force',
    'In labor force:': 'Total_Labor_Force',
    'Not in labor force': 'Not_In_Labor_Force'
})
employment.head()

Employment_Status,State,Armed Forces,Labor_Force,Employed,Total_Labor_Force,Not_In_Labor_Force,Unemployed
0,Alabama,15210,2447875,2344294,2463085,1697053,103581
1,Alaska,26882,363709,342028,390591,195492,21681
2,Arizona,23856,3778884,3606425,3802740,2391066,172459
3,Arkansas,6395,1454780,1399240,1461175,1016030,55540
4,California,148959,20454381,19240700,20603340,11486404,1213681

In [86]:
#Remove Commas From Numbers
cols = employment.columns.drop('State')

employment[cols] = employment[cols].replace(',', '', regex=True)

employment.head()

Employment_Status,State,Armed Forces,Labor_Force,Employed,Total_Labor_Force,Not_In_Labor_Force,Unemployed
0,Alabama,15210,2447875,2344294,2463085,1697053,103581
1,Alaska,26882,363709,342028,390591,195492,21681
2,Arizona,23856,3778884,3606425,3802740,2391066,172459
3,Arkansas,6395,1454780,1399240,1461175,1016030,55540
4,California,148959,20454381,19240700,20603340,11486404,1213681

In [87]:
#Convert Columns to Numeric
employment[cols] = employment[cols].apply(
    pd.to_numeric,
    errors='coerce'
)
employment.head()

Employment_Status,State,Armed Forces,Labor_Force,Employed,Total_Labor_Force,Not_In_Labor_Force,Unemployed
0,Alabama,15210,2447875,2344294,2463085,1697053,103581
1,Alaska,26882,363709,342028,390591,195492,21681
2,Arizona,23856,3778884,3606425,3802740,2391066,172459
3,Arkansas,6395,1454780,1399240,1461175,1016030,55540
4,California,148959,20454381,19240700,20603340,11486404,1213681

In [83]:
employment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  52 non-null     object
 1   Armed Forces           52 non-null     int64
 2   Civilian labor force:  52 non-null     int64
 3   Employed               52 non-null     int64
 4   In labor force:        52 non-null     int64
 5   Not in labor force     52 non-null     int64
 6   Unemployed             52 non-null     int64
dtypes: int64(6), object(1)
memory usage: 3.0+ KB

In [88]:
#Create Employment Rate
employment['Employment_Rate'] = (
    employment['Employed'] /
    employment['Labor_Force']
)

In [89]:
#Create Unemployment Rate
employment['Unemployment_Rate'] = (
    employment['Unemployed'] /
    employment['Labor_Force']
)

In [90]:
employment['Employment_Rate'] = (
    employment['Employment_Rate'] * 100
).round(2)

employment['Unemployment_Rate'] = (
    employment['Unemployment_Rate'] * 100
).round(2)

In [93]:
#Keep only useful columns
employment_cleaned = employment[[
    'State',
    'Labor_Force',
    'Employed',
    'Unemployed',
    'Employment_Rate',
    'Unemployment_Rate'
]]

In [95]:
employment_cleaned.head()

Employment_Status,State,Labor_Force,Employed,Unemployed,Employment_Rate,Unemployment_Rate
0,Alabama,2447875,2344294,103581,95.77,4.23
1,Alaska,363709,342028,21681,94.04,5.96
2,Arizona,3778884,3606425,172459,95.44,4.56
3,Arkansas,1454780,1399240,55540,96.18,3.82
4,California,20454381,19240700,1213681,94.07,5.93

In [96]:
#saved the cleaned Data
employment_cleaned.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Employment_cleaned.csv",index=False)