In [26]:
#Import Liabries
import pandas as pd

In [27]:
#load DataSet
df = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Raw_Data\Median Home Value 2024(1 Year).csv")

In [28]:
#Data Overview
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 107 entries, Label (Grouping) to Puerto Rico!!Margin of Error
dtypes: object(107)
memory usage: 988.0+ bytes

In [29]:
#Remove Margin of Column
df = df.loc[: ,~df.columns.str.contains("Margin of Error")]
df.head()

,Label (Grouping),United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Median value (dollars),"360,600","233,300","376,500","426,000","215,600","759,500","574,600","396,900","371,600",...,"332,600","313,200","545,200","352,800","403,500","602,200","170,800","294,700","339,500","142,100"

In [30]:
#Rename Columns name
df.rename(columns ={"Label (Grouping)": "Metric","Estimate": "Median_Home_Value"}, inplace=True)
df.head()

,Metric,United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Median value (dollars),"360,600","233,300","376,500","426,000","215,600","759,500","574,600","396,900","371,600",...,"332,600","313,200","545,200","352,800","403,500","602,200","170,800","294,700","339,500","142,100"

In [31]:
#Reshape/Transpose Data
homevalue =df.melt(id_vars="Metric",
                var_name="State",
                value_name="Median_Home_Value")
homevalue.head()

                   Metric                    State Median_Home_Value
0  Median value (dollars)  United States!!Estimate           360,600
1  Median value (dollars)        Alabama!!Estimate           233,300
2  Median value (dollars)         Alaska!!Estimate           376,500
3  Median value (dollars)        Arizona!!Estimate           426,000
4  Median value (dollars)       Arkansas!!Estimate           215,600

In [32]:
#Remove “United States” Total Row
homevalue = homevalue[homevalue['State'] != 'United States!!Estimate']
homevalue.head()

                   Metric                 State Median_Home_Value
1  Median value (dollars)     Alabama!!Estimate           233,300
2  Median value (dollars)      Alaska!!Estimate           376,500
3  Median value (dollars)     Arizona!!Estimate           426,000
4  Median value (dollars)    Arkansas!!Estimate           215,600
5  Median value (dollars)  California!!Estimate           759,500

In [33]:
#Clean State Name 
homevalue["State"]=homevalue["State"].str.replace("!!Estimate","")
homevalue.head()

                   Metric       State Median_Home_Value
1  Median value (dollars)     Alabama           233,300
2  Median value (dollars)      Alaska           376,500
3  Median value (dollars)     Arizona           426,000
4  Median value (dollars)    Arkansas           215,600
5  Median value (dollars)  California           759,500

In [34]:
#Remove Commas From Numbers
homevalue['Median_Home_Value'] = (
    homevalue['Median_Home_Value']
    .replace(',', '', regex=True)
)

In [35]:
#Convert Columns to Numeric
homevalue['Median_Home_Value'] = pd.to_numeric(
    homevalue['Median_Home_Value'],
    errors='coerce'
)

In [36]:
#Keep Only Columns need
homevalue = homevalue[['State','Median_Home_Value']]
homevalue.head()

        State  Median_Home_Value
1     Alabama             233300
2      Alaska             376500
3     Arizona             426000
4    Arkansas             215600
5  California             759500

In [37]:
#Check Missing Values
homevalue.isnull().sum()

State                0
Median_Home_Value    0
dtype: int64

In [38]:
homevalue.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 1 to 52
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              52 non-null     object
 1   Median_Home_Value  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [39]:
#save the cleaned Data
homevalue.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Housing_cleaned.csv", index=False)