In [56]:
#Import Liaberies
import pandas as pd

In [57]:
#Load dataSet
df = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Raw_Data\Median Household Income 2024(1 Year).csv")

In [58]:
#Data Overview
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 107 entries, Label (Grouping) to Puerto Rico!!Margin of Error
dtypes: object(107)
memory usage: 988.0+ bytes

In [59]:
#Remove Margin of Error Columns
df = df.loc[: ,~df.columns.str.contains("Margin of Error")]
df.head()

,Label (Grouping),United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Median household income in the past 12 months ...,"81,604","66,659","95,665","81,486","62,106","100,149","97,113","96,049","87,534",...,"71,997","79,721","96,658","82,730","92,090","99,389","60,798","77,488","75,532","27,213"

In [60]:
#Rename Columns Name
df.rename(columns ={"Label (Grouping)": "Metric", "Estimate": "Median_Income"}, inplace=True)
df.head()

,Metric,United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Median household income in the past 12 months ...,"81,604","66,659","95,665","81,486","62,106","100,149","97,113","96,049","87,534",...,"71,997","79,721","96,658","82,730","92,090","99,389","60,798","77,488","75,532","27,213"

In [61]:
#Reshape/Transponse Data
income= df.melt(id_vars="Metric",
                  var_name="State",
                  value_name="Median_Income")
income.head()

,Metric,State,Median_Income
0,Median household income in the past 12 months ...,United States!!Estimate,"81,604"
1,Median household income in the past 12 months ...,Alabama!!Estimate,"66,659"
2,Median household income in the past 12 months ...,Alaska!!Estimate,"95,665"
3,Median household income in the past 12 months ...,Arizona!!Estimate,"81,486"
4,Median household income in the past 12 months ...,Arkansas!!Estimate,"62,106"

In [63]:
#Remove “United States” Total Row
income = income[income['State'] != 'United States!!Estimate']
income.head()

,Metric,State,Median_Income
1,Median household income in the past 12 months ...,Alabama!!Estimate,"66,659"
2,Median household income in the past 12 months ...,Alaska!!Estimate,"95,665"
3,Median household income in the past 12 months ...,Arizona!!Estimate,"81,486"
4,Median household income in the past 12 months ...,Arkansas!!Estimate,"62,106"
5,Median household income in the past 12 months ...,California!!Estimate,"100,149"

In [64]:
#Clean State Name 
income["State"]=income["State"].str.replace("!!Estimate","")
income.head()

                                              Metric       State Median_Income
1  Median household income in the past 12 months ...     Alabama        66,659
2  Median household income in the past 12 months ...      Alaska        95,665
3  Median household income in the past 12 months ...     Arizona        81,486
4  Median household income in the past 12 months ...    Arkansas        62,106
5  Median household income in the past 12 months ...  California       100,149

In [65]:
#Remove Commas From Numbers
income['Median_Income'] = (
    income['Median_Income']
    .replace('[\$,]', '', regex=True)
)

In [66]:
#Convert Columns to Numeric
income['Median_Income'] = pd.to_numeric(
   income['Median_Income'],
    errors='coerce'
)

In [67]:
#Keep Only Columns need
income = income[['State', 'Median_Income']]
income.head()

        State  Median_Income
1     Alabama          66659
2      Alaska          95665
3     Arizona          81486
4    Arkansas          62106
5  California         100149

In [68]:
#Check Missing Values
income.isnull().sum()

State            0
Median_Income    0
dtype: int64

In [70]:
#Data Overview
income.head()
income.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 1 to 52
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          52 non-null     object
 1   Median_Income  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [71]:
#save the cleaned Data
income.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Income_cleaned.csv", index=False)