In [18]:
#Import Liabaries
import pandas as pd

In [19]:
#Load Dataset
df = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Raw_Data\Total Population 2024(1 Year).csv")

In [20]:
#Data Overview
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 107 entries, Label (Grouping) to Puerto Rico!!Margin of Error
dtypes: object(107)
memory usage: 988.0+ bytes

In [21]:
#Remove Margin of Error Column
df = df.loc[:,~df.columns.str.contains("Margin of Error")]
df.head()

,Label (Grouping),United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total,"340,110,990","5,157,699","740,133","7,582,384","3,088,354","39,431,263","5,957,494","3,675,069","1,051,917",...,"7,227,750","31,290,831","3,503,613","648,493","8,811,195","7,958,180","1,769,979","5,960,975","587,618","3,203,295"

In [22]:
#Rename Columns name
df.rename(columns = {"Label (Grouping)":"Category", "Estimate":"Population"},inplace = True)
df.head()

,Category,United States!!Estimate,Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total,"340,110,990","5,157,699","740,133","7,582,384","3,088,354","39,431,263","5,957,494","3,675,069","1,051,917",...,"7,227,750","31,290,831","3,503,613","648,493","8,811,195","7,958,180","1,769,979","5,960,975","587,618","3,203,295"

In [23]:
#Reshape/Transpose of Data
population = df.melt(id_vars="Category",
                  var_name="State",
                  value_name="Population")
population.head()

  Category                    State   Population
0    Total  United States!!Estimate  340,110,990
1    Total        Alabama!!Estimate    5,157,699
2    Total         Alaska!!Estimate      740,133
3    Total        Arizona!!Estimate    7,582,384
4    Total       Arkansas!!Estimate    3,088,354

In [25]:
#Remove “United States” Total Row
population = population[population["State"] != 'United States!!Estimate']
population.head()

  Category                 State  Population
1    Total     Alabama!!Estimate   5,157,699
2    Total      Alaska!!Estimate     740,133
3    Total     Arizona!!Estimate   7,582,384
4    Total    Arkansas!!Estimate   3,088,354
5    Total  California!!Estimate  39,431,263

In [26]:
#Clean State Name 
population["State"]=population["State"].str.replace("!!Estimate","")
population.head()

  Category       State  Population
1    Total     Alabama   5,157,699
2    Total      Alaska     740,133
3    Total     Arizona   7,582,384
4    Total    Arkansas   3,088,354
5    Total  California  39,431,263

In [27]:
#Keep Only Columns need
population = population[['State','Population']]
population.head()

        State  Population
1     Alabama   5,157,699
2      Alaska     740,133
3     Arizona   7,582,384
4    Arkansas   3,088,354
5  California  39,431,263

In [31]:
#Remove Commas
population['Population'] = (
    population['Population']
    .replace(',', '', regex=True)
)

In [32]:
#Convert to Numeric
population['Population'] = pd.to_numeric(
    population['Population'],
    errors='coerce'
)

In [34]:
population.head()
population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 1 to 52
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       52 non-null     object
 1   Population  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [28]:
#Check Missing Values
population.isnull().sum()

State         0
Population    0
dtype: int64

In [35]:
#save the cleaned Data
population.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Population_cleaned.csv", index=False)